config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :restaurants, except: :index do
    resources :tables, only: :create do
      resources :reservations, except: :show
    end
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates_presence_of :start_time, :end_time, :table_id
  validate :check_overlap, if: :table

  belongs_to :table

  def check_overlap
    new_range = start_time..end_time

    is_busy = table.reservations.select { |relation| new_range.overlaps?(relation.start_time..relation.end_time) }

    errors.add(:overbooking, "The table is already booked") unless is_busy.blank?
    is_busy.blank?
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :tables
end

app/models/table.rb
class Table < ActiveRecord::Base
  has_many :reservations
  belongs_to :restaurant

  def reserved?
    self.reservations.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @restaurant = Restaurant.find params[:restaurant_id]
    @table = Table.find params[:table_id]
    @reservations = @table.reservations
  end

  def new
    @reservation = Reservation.new
    @table = Table.find params[:table_id]
  end

  def create
    @reservation = Reservation.new(start_time: params[:reservation][:start_time],
                                   end_time:   params[:reservation][:end_time],
                                   table_id:   params[:table_id])
    if @reservation.save
      redirect_to root_path, notice: "You have successfully booked a table"
    else
      redirect_to new_restaurant_table_reservation_path, alert: @reservation.errors.full_messages
    end
  end

  def edit
    @reservation = Reservation.find params[:id]
  end

  def update
    @reservation = Reservation.find params[:id]
    @reservation.start_time = params[:reservation][:start_time]
    @reservation.end_time   = params[:reservation][:end_time]
    if @reservation.save
      redirect_to restaurant_path(params[:restaurant_id]), notice: "You have successfully booked a table"
    else
      redirect_to :back, alert: @reservation.errors.full_messages
    end
  end

  def destroy
    if Reservation.find(params[:id]).destroy
      redirect_to restaurant_path(params[:restaurant_id]), notice: "Reservation was canceled"
    else
      redirect_to root_path, alert: "Reservation was not canceled"
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find params[:id]
    @our_tables = @restaurant.tables
    # Add first table if restaurant is empty
    @restaurant.tables << Table.new(number: 1) if @our_tables.empty?
  end

  def create
    @restaurant = Restaurant.new name: params[:restaurant][:name]
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: "Restaurant was created successfully"
    else
      redirect_to new_restaurant_path, alert: "Restaurant was not created"
    end
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]
    @restaurant.name = params[:restaurant][:name]
    if @restaurant.save
      redirect_to root_path, notice: "Restaurant was successfully updated"
    else
      redirect_to :back, alert: @restaurant.errors.full_messages
    end
  end

  def destroy
    if Restaurant.find(params[:id]).destroy
      redirect_to root_path, notice: "Restaurant was successfully closed"
    else
      redirect_to root_path, alert: "Restaurant was not closed"
    end
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def create
    restaurant = Restaurant.find params[:restaurant_id]
    table = Table.new(number: restaurant.tables.size + 1)
    if restaurant.tables.size >= 100
      redirect_to :back, alert: "Restaurant is full"
    elsif restaurant.tables << table
      redirect_to :back
    else
      redirect_to :back, alert: table.errors.full_messages
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OnlineBookingProject
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .page-container
      - flash.each do |name, msg|
        - msg = msg.join(" & ") if msg.instance_of? Array
        = content_tag :div, msg, class: "flash #{name}"
      = yield

app/views/reservations/_form.html.haml
= form_for @reservation, url: { action: action }, html: { class: 'forms' } do |f|
  %ul
    %li
      = f.label :start_time, class: 'bold'
      = f.time_field :start_time
    %li
      = f.label :end_time, class: 'bold'
      = f.time_field :end_time

    %li
      = f.submit nil, class: 'btn'
      = link_to 'Cancel', restaurant_table_reservations_path, class: 'btn'

app/views/reservations/edit.html.haml
%h1 Edit Reservation

= form_for(@reservation, url: {action: "update"}) do
  = label_tag(:start_time)
  = time_field(:reservation, :start_time)
  %br
  = label_tag(:end_time)
  = time_field(:reservation, :end_time)
  %br
  = submit_tag("Update Reservation")

app/views/reservations/index.html.haml
- model_class = Reservation
%h1= "#{@restaurant.name}'s Table ##{@table.number} (#{@reservations.size})"

- if @reservations.any?
  %table.striped
    %thead.thead-black
      %tr
        %th= model_class.human_attribute_name(:start_time)
        %th= model_class.human_attribute_name(:end_time)
        %th Management
    %tbody
      - @reservations.each do |reservation|
        %tr
          %td= reservation.start_time.strftime("%a, %l:%M %p")
          %td= reservation.end_time.strftime("%a, %l:%M %p")
          %td
            = link_to 'Correct', edit_restaurant_table_reservation_path(@restaurant, @table, reservation), class: 'btn btn-small'
            = link_to 'Cancel', restaurant_table_reservation_path(@restaurant, @table, reservation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small'

= link_to 'Book a Table', new_restaurant_table_reservation_path, class: 'btn'

app/views/reservations/new.html.haml
%h1= "Book Table ##{@table.number}"
= render partial: "form", locals: { action: "create" }

app/views/restaurants/_form.html.haml
= form_for @restaurant, url: { action: action }, html: { class: 'forms' } do |f|
  %ul
    %li
      = f.label :name, class: 'bold'
      = f.text_field :name

    %li
      = f.submit nil, class: 'btn'
      = link_to 'Cancel', root_path, class: 'btn'

app/views/restaurants/edit.html.haml
%h1 Edit Restaurant
= render partial: "form", locals: { action: "update" }

app/views/restaurants/index.html.haml
- model_class = Restaurant
%h1= pluralize @restaurants.size, model_class.model_name.human

- if @restaurants.any?
  %table.striped
    %thead.thead-black
      %tr
        %th= model_class.human_attribute_name(:name)
        %th Management
    %tbody
      - @restaurants.each do |restaurant|
        %tr
          %td= link_to restaurant.name, restaurant_path(restaurant)
          %td
            = link_to 'Manage', edit_restaurant_path(restaurant), class: 'btn btn-small'
            = link_to 'Close', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small'

= link_to 'Open new Restaurant', new_restaurant_path, class: 'btn'

app/views/restaurants/new.html.haml
%h1 New Restaurant
= render partial: "form", locals: { action: "create" }

app/views/restaurants/show.html.haml
%h1.title= @restaurant.name

= link_to "Add new Table", { action: "create", controller: "tables", restaurant_id: @restaurant.id }, method: :create, class: 'btn'

- if @our_tables.any?
  %table#restaurant-tables
    %tbody
      %tr
        - @our_tables.each_with_index do |table, index|
          - if (index) % 10 == 0
            %tr
          %td{ data: { reserved: table.reserved? } }
            = link_to "Table ##{table.number}", restaurant_table_reservations_path(@restaurant, table)

%div
  = link_to 'Back', root_path, class: 'btn'